spring.application.name=mosad_backend
server.port = ${BACKEND_SERVER_PORT:8080}

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url = jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/mosad
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Configure Mail Services
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Conifgured allowed origins
spring.graphql.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

#Configure Whatsapp Notification
whatsapp.api.url=https://graph.facebook.com/v22.0/
whatsapp.phone.id=519387574600930
whatsapp.access.token=EAAIst5sG4D4BO6PnRZCneG9plbgydAfZAdDwG46ZBN6dQQEP13TonYGh0G8PKHulNZCc9ZCKyx2CsXQDJdZANZC5DCUOSYOXPoyZAXeQV6eBGvVMiPK6aSXy9yCILeRANpAwDhqrDHqGAwkXZAvZC31ziOlGLX7cJRAwfSPhUHOWK3Ox33sN8yhyGC3BiM9ZBW5wGEj2gZDZD


