name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey! This is your first issue. We have missed this issue.Thanks for leting us know. We are looking forward you will contribute in future' first issue"
        pr-message: "We havn't seen you here! Welcome! This is your first PR on this repository. We are looking forward you will contribute in future.carry on..' first pull request"

